# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ucVubJ9WP6l65WyMLZctBFy36ahkcW-X
"""

#modulo
100*(1.02)**24

#Example 02
100*(1.1)**7

"""#Python Code"""

# add
2+2

# subtract
4-3

# multiply
2*10

#modulo
100%2

#modulo
2%100

age = 25

print (age)

# write age, name of a person and height and calculate his age in 10 years and show all variables via print

age = 27
name = "zain ahmed"
Height = 5.4

print(age)
print(name)
print(Height)

#ageIn10 = age + (10)
print(ageIn10)

#type of var
int= 25
str = "name"
float= 25.5
bool = True or False or None

name = "zain"
age = 27
height = 5.4
type(Height)
type(name)
type(age)

savings = int(100)
print(savings)